// generated by contentful-to-sanity
import { defineField, defineType, type SchemaTypeDefinition } from "sanity";

const validateIn = (values: (string | number)[], value: any) =>
  values.includes(value) ? true : `Value must be one of ${values.join(", ")}`;

export const projectType = defineType({
  type: "document",
  name: "project",
  title: "Project",
  description:
    "Project with title, slug, year, main image, thumbnailImage, intro (short text), description and a list of blocks. All blocks can be quite different and they should have their own content type and be linked back to the main project",
  fields: [
    defineField({
      name: "title",
      type: "string",
      title: "Title",
      hidden: false,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "slug",
      type: "slug",
      title: "Slug",
      hidden: false,
      validation: (Rule) => Rule.required(),
      options: { source: "title" },
    }),
    defineField({
      name: "metaDescription",
      type: "string",
      title: "Meta Description",
      hidden: false,
    }),
    defineField({
      name: "intro",
      type: "array",
      of: [{ type: "block" }, { type: "image" }],
      title: "Intro",
      hidden: false,
    }),
    defineField({
      name: "order",
      type: "number",
      title: "Order",
      hidden: false,
      validation: (Rule) => Rule.integer().min(1).max(30),
    }),
    defineField({
      name: "category",
      type: "string",
      title: "Category",
      hidden: false,
      validation: (Rule) =>
        Rule.custom((value) =>
          validateIn(
            ["Packaging", "UX/UI", "Industrial", "Packaging & UI", "OTHER"],
            value
          )
        ),
      options: {
        list: ["Packaging", "UX/UI", "Industrial", "Packaging & UI", "OTHER"],
        layout: "radio",
      },
    }),
    defineField({
      name: "categoryText",
      type: "string",
      title: "Category Text",
      hidden: false,
    }),
    defineField({
      name: "thumbnailImage",
      type: "file",
      title: "Thumbnail image",
      hidden: false,
    }),
    defineField({
      name: "mainImage",
      type: "file",
      title: "Main image",
      hidden: false,
    }),
    defineField({
      name: "isPasswordProtected",
      type: "boolean",
      title: "Is password protected?",
      hidden: false,
      description: "Should this project only be visible behind a password?",
      initialValue: false,
    }),
    defineField({
      name: "protectionPassword",
      type: "string",
      title: "Protection Password",
      hidden: false,
      description:
        'This only works if "is password protected?" is set to true and it is used as a password to show the page',
    }),
    defineField({
      name: "comingSoon",
      type: "boolean",
      title: "Coming Soon",
      hidden: false,
      initialValue: false,
    }),
    defineField({
      name: "blocks",
      type: "array",
      of: [
        {
          type: "reference",
          to: [
            { type: "carouselBlock" },
            { type: "titleTextBlock" },
            { type: "fullScreenBlock" },
            { type: "titlesWithSideParagraphsBlock" },
            { type: "projectInfoBlock" },
            { type: "gridBlock" },
          ],
        },
      ],
      title: "Blocks",
      hidden: false,
      options: { layout: "grid" },
    }),
    defineField({
      type: "boolean",
      description:
        "If this document was archived on Contentful at the time of export, the document will be in a read-only state.",
      name: "contentfulArchived",
      readOnly: true,
    }),
  ],
  preview: { select: { title: "title" } },
  readOnly: ({ document }) =>
    (document == null ? void 0 : document.contentfulArchived) === !0,
});

export const titleTextBlockType = defineType({
  type: "document",
  name: "titleTextBlock",
  title: "Title & Text Block",
  description: "Block containing only a title and text",
  fields: [
    defineField({
      name: "title",
      type: "string",
      title: "Title",
      hidden: false,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "description",
      type: "array",
      of: [
        {
          type: "block",
          styles: [
            { title: "Heading 1", value: "h1" },
            { title: "Heading 2", value: "h2" },
            { title: "Heading 3", value: "h3" },
            { title: "Heading 4", value: "h4" },
            { title: "Heading 5", value: "h5" },
            { title: "Heading 6", value: "h6" },
            { title: "Quote", value: "blockquote" },
          ],
          lists: [
            { title: "Bullet", value: "bullet" },
            { title: "Numbered", value: "number" },
          ],
          marks: {
            decorators: [
              { title: "Strong", value: "strong" },
              { title: "Emphasis", value: "em" },
              { title: "Code", value: "code" },
              { title: "Underline", value: "underline" },
            ],
            annotations: [
              {
                type: "object",
                name: "link",
                title: "url",
                fields: [
                  defineField({
                    type: "string",
                    name: "href",
                    title: "URL",
                    validation: (Rule) => Rule.required(),
                  }),
                  defineField({
                    type: "string",
                    name: "target",
                    title: "Target",
                    options: {
                      list: [
                        { value: "_blank", title: "Blank" },
                        { value: "_parent", title: "Parent" },
                      ],
                    },
                  }),
                ],
              },
              {
                type: "reference",
                name: "reference",
                title: "Reference",
                to: [
                  { type: "project" },
                  { type: "titleTextBlock" },
                  { type: "carouselBlock" },
                  { type: "fullScreenBlock" },
                  { type: "titlesWithSideParagraphsBlock" },
                  { type: "projectInfoBlock" },
                  { type: "gridBlock" },
                  { type: "gridImages" },
                  { type: "homepage" },
                  { type: "aboutPage" },
                ],
              },
              { type: "image" },
              { type: "file" },
            ],
          },
          of: [
            {
              type: "reference",
              title: "Reference",
              to: [
                { type: "project" },
                { type: "titleTextBlock" },
                { type: "carouselBlock" },
                { type: "fullScreenBlock" },
                { type: "titlesWithSideParagraphsBlock" },
                { type: "projectInfoBlock" },
                { type: "gridBlock" },
                { type: "gridImages" },
                { type: "homepage" },
                { type: "aboutPage" },
              ],
            },
          ],
        },
        {
          type: "reference",
          title: "Reference",
          to: [
            { type: "project" },
            { type: "titleTextBlock" },
            { type: "carouselBlock" },
            { type: "fullScreenBlock" },
            { type: "titlesWithSideParagraphsBlock" },
            { type: "projectInfoBlock" },
            { type: "gridBlock" },
            { type: "gridImages" },
            { type: "homepage" },
            { type: "aboutPage" },
          ],
        },
        { type: "image" },
        { type: "file" },
        { type: "break" },
      ],
      title: "Description",
      hidden: false,
    }),
    defineField({
      name: "colorCode",
      type: "string",
      title: "Color Code",
      hidden: false,
      initialValue: "#FFFFFF",
      validation: (Rule) =>
        Rule.custom((value) => validateIn(["#FFFFFF", "#EDB8B8"], value)),
      options: { list: ["#FFFFFF", "#EDB8B8"], layout: "radio" },
    }),
    defineField({
      type: "boolean",
      description:
        "If this document was archived on Contentful at the time of export, the document will be in a read-only state.",
      name: "contentfulArchived",
      readOnly: true,
    }),
  ],
  preview: { select: { title: "title" } },
  readOnly: ({ document }) =>
    (document == null ? void 0 : document.contentfulArchived) === !0,
});

export const carouselBlockType = defineType({
  type: "document",
  name: "carouselBlock",
  title: "Carousel Block",
  description: "A block used to display a carousel of images",
  fields: [
    defineField({
      name: "title",
      type: "string",
      title: "Title",
      hidden: false,
    }),
    defineField({
      name: "carouselDescription",
      type: "array",
      of: [{ type: "block" }, { type: "image" }],
      title: "Description",
      hidden: false,
    }),
    defineField({
      name: "colorCode",
      type: "string",
      title: "Color Code",
      hidden: false,
      validation: (Rule) =>
        Rule.custom((value) => validateIn(["#FFFFFF", "#EDB8B8"], value)),
      options: { list: ["#FFFFFF", "#EDB8B8"], layout: "dropdown" },
    }),
    defineField({
      name: "images",
      type: "array",
      of: [{ type: "file" }],
      title: "Images",
      hidden: false,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      type: "boolean",
      description:
        "If this document was archived on Contentful at the time of export, the document will be in a read-only state.",
      name: "contentfulArchived",
      readOnly: true,
    }),
  ],
  preview: { select: { title: "title" } },
  readOnly: ({ document }) =>
    (document == null ? void 0 : document.contentfulArchived) === !0,
});

export const fullScreenBlockType = defineType({
  type: "document",
  name: "fullScreenBlock",
  title: "Full Screen Block",
  description: "Block to add a full screen image block",
  fields: [
    defineField({
      name: "title",
      type: "string",
      title: "Title",
      hidden: false,
      description:
        "This field does not appear but otherwise it's unclear on Contentful what it is",
    }),
    defineField({
      name: "image",
      type: "file",
      title: "Image",
      hidden: false,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      type: "boolean",
      description:
        "If this document was archived on Contentful at the time of export, the document will be in a read-only state.",
      name: "contentfulArchived",
      readOnly: true,
    }),
  ],
  preview: { select: { title: "title" } },
  readOnly: ({ document }) =>
    (document == null ? void 0 : document.contentfulArchived) === !0,
});

export const titlesWithSideParagraphsBlockType = defineType({
  type: "document",
  name: "titlesWithSideParagraphsBlock",
  title: "Titles with Side Paragraphs Block",
  description: "",
  fields: [
    defineField({
      name: "title1",
      type: "string",
      title: "Title 1",
      hidden: false,
    }),
    defineField({
      name: "description1",
      type: "array",
      of: [{ type: "block" }, { type: "image" }],
      title: "Description 1",
      hidden: false,
    }),
    defineField({
      name: "title2",
      type: "string",
      title: "Title 2",
      hidden: false,
    }),
    defineField({
      name: "description2",
      type: "array",
      of: [{ type: "block" }, { type: "image" }],
      title: "Description 2",
      hidden: false,
    }),
    defineField({
      name: "colorCode",
      type: "string",
      title: "Color Code",
      hidden: false,
      validation: (Rule) =>
        Rule.custom((value) => validateIn(["#FFFFFF", "#EDB8B8"], value)),
      options: { list: ["#FFFFFF", "#EDB8B8"], layout: "radio" },
    }),
    defineField({
      type: "boolean",
      description:
        "If this document was archived on Contentful at the time of export, the document will be in a read-only state.",
      name: "contentfulArchived",
      readOnly: true,
    }),
  ],
  preview: { select: { title: "title1" } },
  readOnly: ({ document }) =>
    (document == null ? void 0 : document.contentfulArchived) === !0,
});

export const projectInfoBlockType = defineType({
  type: "document",
  name: "projectInfoBlock",
  title: "Project Info Block",
  description: "Block containing all the basic project infos",
  fields: [
    defineField({
      name: "title",
      type: "string",
      title: "Title",
      hidden: false,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "subtitle",
      type: "string",
      title: "Subtitle",
      hidden: false,
    }),
    defineField({
      name: "description",
      type: "array",
      of: [
        {
          type: "block",
          styles: [
            { title: "Heading 1", value: "h1" },
            { title: "Heading 2", value: "h2" },
            { title: "Heading 3", value: "h3" },
            { title: "Heading 4", value: "h4" },
            { title: "Heading 5", value: "h5" },
            { title: "Heading 6", value: "h6" },
            { title: "Quote", value: "blockquote" },
          ],
          lists: [
            { title: "Bullet", value: "bullet" },
            { title: "Numbered", value: "number" },
          ],
          marks: {
            decorators: [
              { title: "Strong", value: "strong" },
              { title: "Emphasis", value: "em" },
              { title: "Code", value: "code" },
              { title: "Underline", value: "underline" },
            ],
            annotations: [
              {
                type: "object",
                name: "link",
                title: "url",
                fields: [
                  defineField({
                    type: "string",
                    name: "href",
                    title: "URL",
                    validation: (Rule) => Rule.required(),
                  }),
                  defineField({
                    type: "string",
                    name: "target",
                    title: "Target",
                    options: {
                      list: [
                        { value: "_blank", title: "Blank" },
                        { value: "_parent", title: "Parent" },
                      ],
                    },
                  }),
                ],
              },
              {
                type: "reference",
                name: "reference",
                title: "Reference",
                to: [
                  { type: "project" },
                  { type: "titleTextBlock" },
                  { type: "carouselBlock" },
                  { type: "fullScreenBlock" },
                  { type: "titlesWithSideParagraphsBlock" },
                  { type: "projectInfoBlock" },
                  { type: "gridBlock" },
                  { type: "gridImages" },
                  { type: "homepage" },
                  { type: "aboutPage" },
                ],
              },
              { type: "image" },
              { type: "file" },
            ],
          },
          of: [
            {
              type: "reference",
              title: "Reference",
              to: [
                { type: "project" },
                { type: "titleTextBlock" },
                { type: "carouselBlock" },
                { type: "fullScreenBlock" },
                { type: "titlesWithSideParagraphsBlock" },
                { type: "projectInfoBlock" },
                { type: "gridBlock" },
                { type: "gridImages" },
                { type: "homepage" },
                { type: "aboutPage" },
              ],
            },
          ],
        },
        {
          type: "reference",
          title: "Reference",
          to: [
            { type: "project" },
            { type: "titleTextBlock" },
            { type: "carouselBlock" },
            { type: "fullScreenBlock" },
            { type: "titlesWithSideParagraphsBlock" },
            { type: "projectInfoBlock" },
            { type: "gridBlock" },
            { type: "gridImages" },
            { type: "homepage" },
            { type: "aboutPage" },
          ],
        },
        { type: "image" },
        { type: "file" },
        { type: "break" },
      ],
      title: "Description",
      hidden: false,
    }),
    defineField({ name: "team", type: "string", title: "Team", hidden: false }),
    defineField({
      name: "client",
      type: "string",
      title: "Client",
      hidden: false,
    }),
    defineField({ name: "role", type: "string", title: "Role", hidden: false }),
    defineField({
      name: "skills",
      type: "string",
      title: "Skills",
      hidden: false,
    }),
    defineField({
      type: "boolean",
      description:
        "If this document was archived on Contentful at the time of export, the document will be in a read-only state.",
      name: "contentfulArchived",
      readOnly: true,
    }),
  ],
  preview: { select: { title: "title" } },
  readOnly: ({ document }) =>
    (document == null ? void 0 : document.contentfulArchived) === !0,
});

export const gridBlockType = defineType({
  type: "document",
  name: "gridBlock",
  title: "Grid Block",
  description: "",
  fields: [
    defineField({
      name: "title",
      type: "string",
      title: "Title",
      hidden: false,
      description:
        "This field won't appear on screen but is useful for Contentful",
    }),
    defineField({
      name: "spacing",
      type: "string",
      title: "Spacing",
      hidden: false,
      validation: (Rule) =>
        Rule.custom((value) =>
          validateIn(["xs", "sm", "md", "lg", "xl", "2xl"], value)
        ),
      options: {
        list: ["xs", "sm", "md", "lg", "xl", "2xl"],
        layout: "dropdown",
      },
    }),
    defineField({
      name: "images",
      type: "array",
      of: [{ type: "reference", to: [{ type: "gridImages" }] }],
      title: "Images",
      hidden: false,
    }),
    defineField({
      type: "boolean",
      description:
        "If this document was archived on Contentful at the time of export, the document will be in a read-only state.",
      name: "contentfulArchived",
      readOnly: true,
    }),
  ],
  preview: { select: { title: "title" } },
  readOnly: ({ document }) =>
    (document == null ? void 0 : document.contentfulArchived) === !0,
});

export const gridImagesType = defineType({
  type: "document",
  name: "gridImages",
  title: "Grid Images",
  description: "",
  fields: [
    defineField({
      name: "images",
      type: "array",
      of: [{ type: "file" }],
      title: "Images",
      hidden: false,
    }),
    defineField({
      name: "title",
      type: "string",
      title: "Title",
      hidden: false,
      description: "This won't appear on screen but it's useful for Contentful",
    }),
    defineField({
      type: "boolean",
      description:
        "If this document was archived on Contentful at the time of export, the document will be in a read-only state.",
      name: "contentfulArchived",
      readOnly: true,
    }),
  ],
  preview: { select: { title: "title" } },
  readOnly: ({ document }) =>
    (document == null ? void 0 : document.contentfulArchived) === !0,
});

export const homepageType = defineType({
  type: "document",
  name: "homepage",
  title: "🏠 Homepage",
  description: "Where you can change text about the homepage",
  fields: [
    defineField({
      name: "title",
      type: "string",
      title: "Title",
      hidden: false,
    }),
    defineField({
      name: "quote",
      type: "array",
      of: [
        {
          type: "block",
          marks: {
            decorators: [
              { title: "Strong", value: "strong" },
              { title: "Emphasis", value: "em" },
              { title: "Underline", value: "underline" },
            ],
            annotations: [],
          },
        },
      ],
      title: "Quote",
      hidden: false,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "mainText",
      type: "array",
      of: [
        {
          type: "block",
          styles: [{ title: "Quote", value: "blockquote" }],
          marks: {
            decorators: [
              { title: "Strong", value: "strong" },
              { title: "Emphasis", value: "em" },
              { title: "Underline", value: "underline" },
            ],
            annotations: [],
          },
        },
      ],
      title: "Main Text",
      hidden: false,
    }),
    defineField({
      type: "boolean",
      description:
        "If this document was archived on Contentful at the time of export, the document will be in a read-only state.",
      name: "contentfulArchived",
      readOnly: true,
    }),
  ],
  preview: { select: { title: "title" } },
  readOnly: ({ document }) =>
    (document == null ? void 0 : document.contentfulArchived) === !0,
});

export const aboutPageType = defineType({
  type: "document",
  name: "aboutPage",
  title: "👩🏼\u200d💼 About Page",
  description: "Where you can change the copy about the about page",
  fields: [
    defineField({
      name: "title",
      type: "string",
      title: "Title",
      hidden: false,
    }),
    defineField({
      name: "headerText",
      type: "array",
      of: [
        {
          type: "block",
          marks: {
            decorators: [
              { title: "Strong", value: "strong" },
              { title: "Emphasis", value: "em" },
              { title: "Underline", value: "underline" },
            ],
            annotations: [
              {
                type: "object",
                name: "link",
                title: "url",
                fields: [
                  defineField({
                    type: "string",
                    name: "href",
                    title: "URL",
                    validation: (Rule) => Rule.required(),
                  }),
                  defineField({
                    type: "string",
                    name: "target",
                    title: "Target",
                    options: {
                      list: [
                        { value: "_blank", title: "Blank" },
                        { value: "_parent", title: "Parent" },
                      ],
                    },
                  }),
                ],
              },
              {
                type: "reference",
                name: "reference",
                title: "Reference",
                to: [{ type: "project" }],
              },
            ],
          },
        },
      ],
      title: "Header Text",
      hidden: false,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      type: "boolean",
      description:
        "If this document was archived on Contentful at the time of export, the document will be in a read-only state.",
      name: "contentfulArchived",
      readOnly: true,
    }),
  ],
  preview: { select: { title: "title" } },
  readOnly: ({ document }) =>
    (document == null ? void 0 : document.contentfulArchived) === !0,
});

export const breakType = defineType({
  name: "break",
  title: "Break",
  type: "object",
  fields: [
    defineField({
      name: "style",
      type: "string",
      options: {
        list: [
          { title: "Line break", value: "lineBreak" },
          { title: "Read more", value: "readMore" },
        ],
      },
    }),
  ],
});

export const types = [
  projectType,
  titleTextBlockType,
  carouselBlockType,
  fullScreenBlockType,
  titlesWithSideParagraphsBlockType,
  projectInfoBlockType,
  gridBlockType,
  gridImagesType,
  homepageType,
  aboutPageType,
  breakType,
] satisfies SchemaTypeDefinition[];
